### ISSUE TITLE
Create Certification Documentation

### ISSUE THREAD

**Issue by ramirezg** [18F/control-masonry#13]
Currently the certification documentation is stored in [Yaml files](https://github.com/18F/control-masonry/tree/master/completed_certifications). We'll need to convert them into different formats:

1. Browsable static documentation site using [US Web Design Standards](https://playbook.cio.gov/designstandards/)
2. Export to PDF/Docx

**Comment by joshuamckenty** [comment]
This is why we started in gitbook in the first place, though. Does it not seem workable for some reason?

**Comment by ramirezg** [comment]
@joshuamckenty gitbook worked. hopefully we'll be added more renders as needed.

**Comment by joshuamckenty** [comment]
Sweet! I love the code for converting yaml to markdown, too. Do you mind if I extract that into a general purpose library?
