### ISSUE TITLE
Controls nav menu being cut off for long list of controls

### ISSUE THREAD

**Issue by gregelin** [18F/control-masonry#21]
Chrome is showing `.nav-children` with a `max-hight: 400px;`. This is limiting the number of controls showing up in the rendered pages. There is currently no overflow setting, either. The end result is it appears many controls are missing after the page generation.

```
.nav-children {
    display: block;
    max-height: 400px;
    opacity: 1;
    -webkit-transition: max-height .2s, opacity .2s;
    -moz-transition: max-height .2s, opacity .2s;
    -o-transition: max-height .2s, opacity .2s;
    transition: max-height .2s, opacity .2s;
}
```

Best solution might be an `overflow: scroll;`.

**Comment by ramirezg** [comment]
@gregelin Submitted an issue to the [template repo](https://github.com/18F/guides-template/issues/63)

**Comment by ramirezg** [comment]
@gregelin updated `guides_style_18f` template, but also working on a gitbook renderer.
